// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewPinpadApi.Data;

#nullable disable

namespace NewPinpadApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250827082331_EditSysMenu")]
    partial class EditSysMenu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewPinpadApi.Models.Audit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTimes")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("NewPinpadApi.Models.Dashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Inactive")
                        .HasColumnType("int");

                    b.Property<int>("Maintenance")
                        .HasColumnType("int");

                    b.Property<int>("NotReady")
                        .HasColumnType("int");

                    b.Property<int>("Ready")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("NewPinpadApi.Models.DeviceTranslog", b =>
                {
                    b.Property<int>("TranslogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TranslogId"));

                    b.Property<string>("TranslogAcctnum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TranslogAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TranslogBranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TranslogCardnum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranslogCreateby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TranslogCreatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TranslogRc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranslogRrn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranslogSn")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TranslogTrxType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TranslogId");

                    b.HasIndex("TranslogBranch");

                    b.HasIndex("TranslogSn");

                    b.HasIndex("TranslogTrxType");

                    b.ToTable("DeviceTranslogs");
                });

            modelBuilder.Entity("NewPinpadApi.Models.LinkLevelMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("MenuId");

                    b.ToTable("LinkLevelMenus");
                });

            modelBuilder.Entity("NewPinpadApi.Models.OtaFile", b =>
                {
                    b.Property<int>("OtaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtaId"));

                    b.Property<string>("OtaAttachment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtaCreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OtaCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtaDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtaFilename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OtaKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OtaStatus")
                        .HasColumnType("int");

                    b.Property<string>("OtaUpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OtaUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OtaId");

                    b.ToTable("OtaFiles");
                });

            modelBuilder.Entity("NewPinpadApi.Models.OtaFileAssign", b =>
                {
                    b.Property<int>("OtaassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtaassId"));

                    b.Property<string>("OtaassBranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("OtaassKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OtaassId");

                    b.HasIndex("OtaassBranch");

                    b.HasIndex("OtaassKey");

                    b.ToTable("OtaFileAssigns");
                });

            modelBuilder.Entity("NewPinpadApi.Models.Pinpad", b =>
                {
                    b.Property<int>("PpadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PpadId"));

                    b.Property<string>("PpadBranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PpadBranchLama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PpadCreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PpadCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PpadFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PpadLastActivity")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PpadLastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PpadSn")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PpadStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PpadStatusLama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PpadStatusRepair")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PpadTid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PpadUpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PpadUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PpadId");

                    b.HasIndex("PpadBranch");

                    b.HasIndex("PpadStatusRepair");

                    b.ToTable("Pinpads");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysArea", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("SysAreas");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysBranch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ctrlbr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ppad_iphigh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ppad_iplow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ppad_seq")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Area");

                    b.HasIndex("Type");

                    b.ToTable("SysBranches");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysBranchType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SysBranchTypes");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SysLevels");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Urls")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("SysMenus");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysMkey", b =>
                {
                    b.Property<int>("MkeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mkey_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MkeyId"));

                    b.Property<string>("MkeyCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mkey_code");

                    b.Property<string>("MkeyCreateBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mkey_createby");

                    b.Property<DateTime>("MkeyCreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("mkey_createdate");

                    b.Property<string>("MkeyDesc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mkey_desc");

                    b.Property<string>("MkeyNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("mkey_number");

                    b.Property<string>("MkeyUpdateBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mkey_updateby");

                    b.Property<DateTime?>("MkeyUpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("mkey_updatedate");

                    b.HasKey("MkeyId");

                    b.ToTable("SysMkey");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysResponseCode", b =>
                {
                    b.Property<int>("RescodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RescodeId"));

                    b.Property<string>("RescodeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RescodeCreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RescodeCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RescodeDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RescodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RescodeUpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RescodeUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RescodeId");

                    b.ToTable("SysResponseCodes");
                });

            modelBuilder.Entity("NewPinpadApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevel");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NewPinpadApi.Models.DeviceTranslog", b =>
                {
                    b.HasOne("NewPinpadApi.Models.SysBranch", "Branch")
                        .WithMany("DeviceTranslogs")
                        .HasForeignKey("TranslogBranch")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NewPinpadApi.Models.Pinpad", "Pinpad")
                        .WithMany("DeviceTranslogs")
                        .HasForeignKey("TranslogSn")
                        .HasPrincipalKey("PpadSn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NewPinpadApi.Models.SysResponseCode", "TransactionType")
                        .WithMany("DeviceTranslogs")
                        .HasForeignKey("TranslogTrxType")
                        .HasPrincipalKey("RescodeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Pinpad");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("NewPinpadApi.Models.LinkLevelMenu", b =>
                {
                    b.HasOne("NewPinpadApi.Models.SysLevel", "SysLevel")
                        .WithMany("LinkLevelMenus")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewPinpadApi.Models.SysMenu", "SysMenu")
                        .WithMany("LinkLevelMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SysLevel");

                    b.Navigation("SysMenu");
                });

            modelBuilder.Entity("NewPinpadApi.Models.OtaFileAssign", b =>
                {
                    b.HasOne("NewPinpadApi.Models.SysBranch", "Branch")
                        .WithMany("OtaFileAssigns")
                        .HasForeignKey("OtaassBranch")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewPinpadApi.Models.OtaFile", "OtaFile")
                        .WithMany("Assignments")
                        .HasForeignKey("OtaassKey")
                        .HasPrincipalKey("OtaKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("OtaFile");
                });

            modelBuilder.Entity("NewPinpadApi.Models.Pinpad", b =>
                {
                    b.HasOne("NewPinpadApi.Models.SysBranch", "Branch")
                        .WithMany("Pinpads")
                        .HasForeignKey("PpadBranch")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewPinpadApi.Models.SysResponseCode", "StatusRepairCode")
                        .WithMany("Pinpads")
                        .HasForeignKey("PpadStatusRepair")
                        .HasPrincipalKey("RescodeCode");

                    b.Navigation("Branch");

                    b.Navigation("StatusRepairCode");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysBranch", b =>
                {
                    b.HasOne("NewPinpadApi.Models.SysArea", "SysArea")
                        .WithMany("Branches")
                        .HasForeignKey("Area")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewPinpadApi.Models.SysBranchType", "SysBranchType")
                        .WithMany("Branches")
                        .HasForeignKey("Type")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SysArea");

                    b.Navigation("SysBranchType");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysMenu", b =>
                {
                    b.HasOne("NewPinpadApi.Models.SysMenu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NewPinpadApi.Models.User", b =>
                {
                    b.HasOne("NewPinpadApi.Models.SysLevel", "SysLevel")
                        .WithMany("Users")
                        .HasForeignKey("AccessLevel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SysLevel");
                });

            modelBuilder.Entity("NewPinpadApi.Models.OtaFile", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("NewPinpadApi.Models.Pinpad", b =>
                {
                    b.Navigation("DeviceTranslogs");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysArea", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysBranch", b =>
                {
                    b.Navigation("DeviceTranslogs");

                    b.Navigation("OtaFileAssigns");

                    b.Navigation("Pinpads");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysBranchType", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysLevel", b =>
                {
                    b.Navigation("LinkLevelMenus");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysMenu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("LinkLevelMenus");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysResponseCode", b =>
                {
                    b.Navigation("DeviceTranslogs");

                    b.Navigation("Pinpads");
                });
#pragma warning restore 612, 618
        }
    }
}
