// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewPinpadApi.Data;

#nullable disable

namespace NewPinpadApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250814230037_AddDashboard")]
    partial class AddDashboard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewPinpadApi.Models.Audit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTimes")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("NewPinpadApi.Models.Dashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Inactive")
                        .HasColumnType("int");

                    b.Property<int>("Maintenance")
                        .HasColumnType("int");

                    b.Property<int>("NotReady")
                        .HasColumnType("int");

                    b.Property<int>("Ready")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("NewPinpadApi.Models.Pinpad", b =>
                {
                    b.Property<int>("PpadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PpadId"));

                    b.Property<string>("PpadBranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PpadBranchLama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PpadCreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PpadCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PpadFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PpadLastActivity")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PpadLastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PpadSn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PpadStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PpadStatusLama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PpadStatusRepair")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PpadTid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PpadUpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PpadUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PpadId");

                    b.HasIndex("PpadBranch");

                    b.HasIndex("PpadStatusRepair");

                    b.ToTable("Pinpads");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysArea", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("SysAreas");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysBranch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ctrlbr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ppad_iphigh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ppad_iplow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ppad_seq")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Area");

                    b.HasIndex("Type");

                    b.ToTable("SysBranches");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysBranchType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SysBranchTypes");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysResponseCode", b =>
                {
                    b.Property<int>("RescodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RescodeId"));

                    b.Property<string>("RescodeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RescodeCreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RescodeCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RescodeDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RescodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RescodeUpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RescodeUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RescodeId");

                    b.ToTable("SysResponseCodes");
                });

            modelBuilder.Entity("NewPinpadApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NewPinpadApi.Models.Pinpad", b =>
                {
                    b.HasOne("NewPinpadApi.Models.SysBranch", "Branch")
                        .WithMany("Pinpads")
                        .HasForeignKey("PpadBranch")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewPinpadApi.Models.SysResponseCode", "StatusRepairCode")
                        .WithMany("Pinpads")
                        .HasForeignKey("PpadStatusRepair")
                        .HasPrincipalKey("RescodeCode");

                    b.Navigation("Branch");

                    b.Navigation("StatusRepairCode");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysBranch", b =>
                {
                    b.HasOne("NewPinpadApi.Models.SysArea", "SysArea")
                        .WithMany("Branches")
                        .HasForeignKey("Area")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewPinpadApi.Models.SysBranchType", "SysBranchType")
                        .WithMany("Branches")
                        .HasForeignKey("Type")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SysArea");

                    b.Navigation("SysBranchType");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysArea", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysBranch", b =>
                {
                    b.Navigation("Pinpads");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysBranchType", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("NewPinpadApi.Models.SysResponseCode", b =>
                {
                    b.Navigation("Pinpads");
                });
#pragma warning restore 612, 618
        }
    }
}
