// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewPinpadApi.Data;

#nullable disable

namespace NewPinpadApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewPinpadApi.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpHigh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpLow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentBranchId")
                        .HasColumnType("int");

                    b.Property<int>("RegionalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentBranchId");

                    b.HasIndex("RegionalId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("NewPinpadApi.Models.DeviceLog", b =>
                {
                    b.Property<int>("DevlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DevlogId"));

                    b.Property<string>("DevlogBranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevlogCreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DevlogCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DevlogSn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevlogStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevlogTrxCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DevlogId");

                    b.ToTable("DeviceLogs");
                });

            modelBuilder.Entity("NewPinpadApi.Models.Pinpad", b =>
                {
                    b.Property<int>("PpadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PpadId"));

                    b.Property<int>("PpadBranch")
                        .HasColumnType("int");

                    b.Property<int>("PpadBranchLama")
                        .HasColumnType("int");

                    b.Property<string>("PpadCreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PpadCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PpadFlag")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PpadLastActivity")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PpadLastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PpadSn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PpadStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PpadStatusLama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PpadStatusRepair")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PpadTid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PpadUpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PpadUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PpadId");

                    b.HasIndex("PpadBranch");

                    b.ToTable("Pinpads");
                });

            modelBuilder.Entity("NewPinpadApi.Models.Regional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regionals");
                });

            modelBuilder.Entity("NewPinpadApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NewPinpadApi.Models.Branch", b =>
                {
                    b.HasOne("NewPinpadApi.Models.Branch", "ParentBranch")
                        .WithMany("ChildBranches")
                        .HasForeignKey("ParentBranchId");

                    b.HasOne("NewPinpadApi.Models.Regional", "Regional")
                        .WithMany("Branches")
                        .HasForeignKey("RegionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentBranch");

                    b.Navigation("Regional");
                });

            modelBuilder.Entity("NewPinpadApi.Models.Pinpad", b =>
                {
                    b.HasOne("NewPinpadApi.Models.Branch", "Branch")
                        .WithMany("Pinpads")
                        .HasForeignKey("PpadBranch")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("NewPinpadApi.Models.Branch", b =>
                {
                    b.Navigation("ChildBranches");

                    b.Navigation("Pinpads");
                });

            modelBuilder.Entity("NewPinpadApi.Models.Regional", b =>
                {
                    b.Navigation("Branches");
                });
#pragma warning restore 612, 618
        }
    }
}
